"""Pydantic models for request/response validation."""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional


# ── Profile ───────────────────────────────────────────────────────────────────

class Measurements(BaseModel):
    chest: str = ""
    waist: str = ""
    inseam: str = ""
    neck: str = ""
    shoulder_width: str = ""
    shoe_size: str = ""


class Sizes(BaseModel):
    shirt: str = ""
    pants: str = ""
    shoe: str = ""


class CategoryBudget(BaseModel):
    """Per-category budget overrides. 0 means fall back to global budget_max."""
    tops: float = 0.0
    bottoms: float = 0.0
    outerwear: float = 0.0
    shoes: float = 0.0


class UserProfile(BaseModel):
    id: int = 1
    height: str = ""
    skin_color: str = ""
    photo_path: str = ""
    measurements: Measurements = Field(default_factory=Measurements)
    sizes: Sizes = Field(default_factory=Sizes)
    brands_liked: list[str] = Field(default_factory=list)
    budget_min: float = 40.0
    budget_max: float = 120.0
    colors_preferred: list[str] = Field(default_factory=list)
    fit_preference: str = "regular"
    bottom_fit: str = "slim"    # slim | regular | relaxed
    bottom_rise: str = "low"    # low | mid | high
    occasion: str = "casual"
    style_notes: str = ""
    dislikes: list[str] = Field(default_factory=list)
    budget_per_category: CategoryBudget = Field(default_factory=CategoryBudget)


class ProfileUpdate(BaseModel):
    """Fields that can be updated on the profile."""
    height: Optional[str] = None
    skin_color: Optional[str] = None
    measurements: Optional[Measurements] = None
    sizes: Optional[Sizes] = None
    brands_liked: Optional[list[str]] = None
    budget_min: Optional[float] = None
    budget_max: Optional[float] = None
    colors_preferred: Optional[list[str]] = None
    fit_preference: Optional[str] = None
    bottom_fit: Optional[str] = None
    bottom_rise: Optional[str] = None
    occasion: Optional[str] = None
    style_notes: Optional[str] = None
    dislikes: Optional[list[str]] = None
    budget_per_category: Optional[CategoryBudget] = None


# ── Products & Outfits ────────────────────────────────────────────────────────

class Product(BaseModel):
    """A product discovered via Perplexity search."""
    product_name: str
    brand: str = ""
    category: str = ""        # top, bottom, outerwear, shoes, belt, accessory
    formality_tier: str = ""  # transient — not persisted to DB
    color: str = ""
    size: str = ""
    price: float = 0.0
    retailer: str = ""
    purchase_url: str = ""
    image_url: str = ""
    return_policy_days: int = 30
    return_policy_summary: str = ""

class OutfitItem(BaseModel):
    """A product assigned to an outfit group by the LLM."""
    product: Product
    outfit_group: int
    is_wildcard: bool = False
    stylist_note: str = ""


class TrunkItemResponse(BaseModel):
    id: int
    trunk_id: int
    product_name: str = "Unknown"
    brand: str = ""
    category: str = ""
    color: str = ""
    size: str = ""
    price: float = 0.0
    retailer: str = ""
    purchase_url: str = ""
    image_url: str = ""
    return_policy_days: int = 30
    return_policy_summary: str = ""
    outfit_group: int = 0
    is_wildcard: bool = False
    decision: str = ""
    returned: bool = False
    stylist_note: str = ""
    outfit_description: str = ""
    feedback_reason: str = ""
    feedback_text: str = ""


class TrunkResponse(BaseModel):
    """Response model for a trunk."""
    id: int
    generated_at: str
    season: str
    stylist_brief: str
    status: str
    items: list[TrunkItemResponse] = Field(default_factory=list)


class DecisionRequest(BaseModel):
    """Request to record a purchase/skip decision."""
    decision: str  # "purchase", "skip", "dislike"


class FeedbackPayload(BaseModel):
    """Detailed feedback for a dislike."""
    reason: str  # "Color", "Style", "Article", "Other"
    text: str = ""


class ReturnRequest(BaseModel):
    """Request to mark an item as returned."""
    returned: bool = True


class RerollRequest(BaseModel):
    locked_item_ids: list[int] = Field(default_factory=list)


# ── LLM ───────────────────────────────────────────────────────────────────────

class StylistBrief(BaseModel):
    """Generated stylist brief text."""
    brief: str


class SearchQuery(BaseModel):
    """A single search query for product discovery."""
    query: str
    target_category: str = ""    # what slot this fills
    is_wildcard: bool = False


class SearchQueriesResponse(BaseModel):
    """Set of search queries generated by the LLM."""
    queries: list[SearchQuery]


class OutfitAssembly(BaseModel):
    """A curated outfit from the LLM."""
    outfit_group: int
    is_wildcard: bool = False
    items: list[OutfitItem] = Field(default_factory=list)
    outfit_description: str = ""


class CurationResult(BaseModel):
    """Full curation output: multiple outfits."""
    outfits: list[OutfitAssembly] = Field(default_factory=list)


# ── Style Learning ────────────────────────────────────────────────────────────

class StyleWeight(BaseModel):
    dimension: str     # brand, color, category, fit, price_range
    value: str
    weight: float
